# <font color=darkblue> Part 1: Exploring NumPy </font>

In [62]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [63]:
# Create a vector as a column
vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

In [64]:
# Create a matrix
matrix = np.array([[1, 2],[1, 2],[1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [65]:
# Type of the matrix
type(matrix)

numpy.ndarray

In [66]:
# Initializing an array with all '1' values
np.ones( (3,4), dtype=np.int16 )  

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [67]:
# Initializing an array of with some value
np.full( (3,4), 0.11 )  

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [68]:
# Arrange an array of intervals
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [69]:
# Arrange an array of intervals
np.arange( 0, 2, 0.3 )             

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [82]:
# Generate random samples 
np.random.rand(2,3)

array([[0.40466068, 0.35576408, 0.92568251],
       [0.44686637, 0.89457949, 0.25637727]])

### Some other important attributes

Some of the important attributes of a NumPy object are:
1.	Ndim: displays the dimension of the array
2.	Shape: returns a tuple of integers indicating the size of the array
3.	Size: returns the total number of elements in the NumPy array
4.	Dtype: returns the type of elements in the array, i.e., int64, character
5.	Itemsize: returns the size in bytes of each item
6.	Reshape: Reshapes the NumPy array

### Examples of Indexing

- 	A[2:5] will print items 2 to 4. Index in NumPy arrays starts from 0
- 	A[2::2] will print items 2 to end skipping 2 items
- 	A[::-1] will print the array in the reverse order
- 	A[1:] will print from row 1 to end


# <font color=darkblue> Part 2: Exploring pandas </font>

In [88]:
#Import library
import pandas as pd

#Creating a dataframe
people_dict = { "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),   
                "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"]),
                "children": pd.Series([0, 3], index=["charles", "bob"]),
                "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),}
people = pd.DataFrame(people_dict)
people

weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

In [89]:
# Selecting only people born before 1990
people[people["birthyear"] < 1990]

weight  birthyear  children    hobby
alice      68       1985       NaN   Biking
bob        83       1984       3.0  Dancing

### Some essential methods in dataframes:

1.	head(): returns the top 5 rows in the dataframe object
2.	tail(): returns the bottom 5 rows in the dataframe
3.	info(): prints the summary of the dataframe
4.	describe(): gives a nice overview of the main aggregated values over each column


# <font color=darkblue> Part 3: Writing custom functions </font>

In [49]:
#Importing libraries
import os
import tarfile
import urllib

#Defining URL and PATH constants
DATA_URL = "http://www.realclimate.org/data/senators_sunspots.txt"
DATA_PATH = os.path.join("datasets", "demo1DataSet")

In [ ]:
# My custom function to fetch data from a web URL
def fetch_data_from_url(data_url=DATA_URL, data_path=DATA_PATH):
    if not os.path.isdir(data_path):
        os.makedirs(data_path)
    txt_path = os.path.join(data_path, "demo1.txt")
    urllib.request.urlretrieve(data_url, txt_path)
    txt_file = open(txt_path, "r")
#     print(txt_file.read())

In [50]:
# Calling the custom fetch function
fetch_data_from_url()

In [51]:
# Import libraries
import pandas as pd

# My custom function to load data from the database
def load_data(data_path=DATA_PATH):
    print(DATA_PATH)
    txt_path = os.path.join(data_path, "demo1.txt")
    return pd.read_csv(txt_path)

In [52]:
# Verifying my data
data = load_data()
data.head()

datasets/demo1DataSet


Republicans in Senate  (Since 1959)
0                                Year
1                            Number  
2          Yr   Republicans_in_Senate
3                         1960 36\t\t
4                         1962 34\t\t